# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hybrid' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hybrid

  target 'hybrid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hybridTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hybrid-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hybrid-tvOS

  target 'hybrid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
